### ISSUE TITLE
Support multiple backgrounds and foregrounds

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/preact-stickerbook#5]
Lately in the apps I'm building, I'm finding a need to create non-editable, "in-between" layers, which sit above backgrounds but below stickers. Essentially, stacked backgrounds.

My suggestion is that we add the option to pass an _array_ of backgrounds to the `background` prop, so that the export of this intermediate layer can be compiled in the Stickerbook itself, rather than manually layering things together.

**Comment by marlonmarcello** [comment]
Agreed! Both `background` and `foreground` should accept arrays.

**Comment by liamegan** [comment]
Agreed.
